const data = {
  products: [
    {
      _id: "1",
      name: "Nike green T shirt",
      category: "T Shirts",
      image: "/images/p2.jpg",
      price: 45,
      countInStock: 10,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      discription: "high quality product",
    },
    {
      _id: "2",
      name: "Polo T shirt",
      category: "T Shirts",
      image: "/images/p3.jpg",
      price: 60,
      countInStock: 20,
      brand: "Polo",
      rating: 5,
      numReviews: 14,
      discription: "high quality product",
    },
    {
      _id: "3",
      name: "Polo bleu T shirt",
      category: "T Shirts",
      image: "/images/p4.jpg",
      price: 40,
      countInStock: 0,
      brand: "Adidas",
      rating: 4,
      numReviews: 12,
      discription: "high quality product",
    },
    {
      _id: "4",
      name: "Adidas T shirt",
      category: "T Shirts",
      image: "/images/p5.jpg",
      price: 35,
      countInStock: 5,
      brand: "Adidas",
      rating: 2.5,
      numReviews: 10,
      discription: "high quality product",
    },
    {
      _id: "5",
      name: "Nike T shirt",
      category: "T Shirts",
      image: "/images/p6.jpg",
      price: 50,
      countInStock: 12,
      brand: "Nike",
      rating: 4,
      numReviews: 13,
      discription: "high quality product",
    },
    {
      _id: "6",
      name: "Lacost white T shirt",
      category: "T Shirts",
      image: "/images/p7.jpg",
      price: 55,
      countInStock: 7,
      brand: "Lacost",
      rating: 5,
      numReviews: 10,
      discription: "high quality product",
    },
    {
      _id: "7",
      name: "Lacost green T shirt",
      category: "T Shirts",
      image: "/images/p8.jpg",
      price: 55,
      countInStock: 18,
      brand: "Lacost",
      rating: 5,
      numReviews: 16,
      discription: "high quality product",
    },
  ],
};

export default data;
